spring :
  profiles:
    active:
      - EN
      - cat
      - prod
guru :
  username : usernameYaml
  password : mdpYaml
  jdbcurl : urlYaml

---
spring:
  profiles: prod
guru :
  username : usernameProdYaml
  password : mdpProdYaml
  jdbcurl : urlProdYaml